// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CalHash(arg1:Array<string>,arg2:string):Promise<Array<main.Hasher>>;

export function Greet(arg1:string):Promise<string>;

export function StopHash():Promise<void>;
